version: '3.8'

services:
  php:
    container_name: php-camagru
    build:
      context: ./php
    env_file:
      - .env
    volumes:
      - ./php:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - app
    depends_on:
      - mysql
    restart: always
    command: sh -c "chown -R www-data:www-data /var/www/html/rsrcs/public && chmod -R 775 /var/www/html/rsrcs/public && npx tailwindcss build /var/www/html/srcs/styles/input.css -o /var/www/html/srcs/styles/output.css && php-fpm"

  nginx:
    container_name: nginx-camagru
    image: nginx:latest
    volumes:
      - ./php:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - php
    networks:
      - app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-camagru
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-camagru
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge
